title: Your TomTom Maps APIs Journey
tagline: Learn to use the TomTom Maps SDK for Web
description: Learn to use the TomTom Maps SDK for Web to add location to your apps
template:
  repo: your-journey-template
  name: your-journey
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Getting your API KEY
    description: The first step in your course is to get your API KEY from developer.tomtom.com
    event: issues.assigned
    link: 'https://developer.tomtom.com'
    actions:
      - type: closeIssue
