title: Your TomTom Maps APIs Journey
tagline: Learn to use the TomTom Maps SDK for Web
description: Learn to use the TomTom Maps SDK for Web to add location to your apps
template:
  repo: your-journey-template
  name: my-tomtom-maps-journey
steps:
  - title: Getting your API KEY
    description: >-
      The first step in your course is to get your API KEY from
      developer.tomtom.com
    event: pull_request.assigned
    link: 'https://developer.tomtom.com'
    actions:
      - type: createPullRequest
        title: Add API KEY
        body: add-key.md
        head: master
  - title: Add a map to your website
    description: How to add a simple map view into your project.
    event: pull_request.assigned
    actions:
      - type: createPullRequest
        title: Add Map
        body: add-map.md
        head: master
  - title: Show traffic in your map
    description: How to add a simple trafic flow layer
    event: pull_request.assigned
    actions:
      - type: createPullRequest
        title: Add Traffic
        body: add-traffic.md
        head: master
  - title: Click click and here is the address
    description: How to use the Reverse Geocoding from the Search API
    event: pull_request.assigned
    actions:
      - type: createPullRequest
        title: Add Reverse Geocoding
        body: add-reverse-geocoding.md
        head: master
  - title: We are talking a walk
    description: Using the Routing API we are going to build pedestrian routes
    event: pull_request.assigned
    actions:
      - type: createPullRequest
        title: Create Route
        body: add-route.md
        head: master
  - title: Let us get Coffee!
    description: >-
      Using the search along the route, we get Point of interests that are
      around our route.
    event: pull_request.assigned
    actions:
      - type: createPullRequest
        title: Search Along Route
        body: add-search.md
        head: master
  - title: Congratulations!
    event: pull_request.assigned
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    description: You have finish this tutorial!
